// 定义 修改动作
export const SET_LOADING = 'SET_PLAYING_STATE'

export const SET_PLAYING_STATE = 'SET_PLAYING_STATE'
export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'
export const SET_PLAYLIST = 'SET_PLAYLIST'
export const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'
export const SET_PLAY_MODE = 'SET_PLAY_MODE'
export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX '
export const ADD_PLAYLIST = 'ADD_PLAYLIST '
export const SET_TARBAR = 'SET_TARBAR'
